### ISSUE TITLE
ДЗ-3 правки

### ISSUE THREAD

**Issue by Dexter19** [ProfDenDev/profden#3]
Почний робити ДЗ з самого початку чітко по пунктам як в завданні. Бо в тебе там багато не зрозумілого вмісту в файлах. + створи папку css та файл в ній як сказано в завданні.

**Comment by ProfDenDev** [comment]
А куски текста, вставлять в файл readme.rm ?

пн, 12 февр. 2024 г., 20:51 Nick ***@***.***>:

**Comment by Dexter19** [comment]
index.html або інші html файли в залежності від умови.
